# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_patient', to='records.Patient'),
        ),
        migrations.AlterField(
            model_name='record',
            name='session_resume',
            field=models.CharField(max_length=5200),
        ),
    ]
